In [ ]:
import pandas as pd

Genshin_Banner = pd.read_csv('genshin_banner_history_eurogamer.csv')
Genshin_Banner

,Banner Name,5-Star Character,4-Star Characters,Banner Dates
0,Ballad in Goblets,Venti,"Barbara, Fischl, Xiangling","28th September, 2020 to 18th October, 2020"
1,Sparkling Steps,Klee,"Noelle, Sucrose, Xingqiu","20th October, 2020 to 10th November, 2020"
2,Farewell of Snezhnaya,Tartaglia (Childe),"Beidou, Diona, Ningguang","11th November, 2020 to 1st December, 2020"
3,Gentry of Hermitage,Zhongli,"Chonyun, Razor, Xinyan","1st December, 2020 to 22nd December, 2020"
4,Secretum Secretorum,Albedo,"Bennett, Fischl, Sucrose","23rd December, 2020 to 12th January, 2021"
...,...,...,...,...
127,The Hearth's Ashen Shadow,Arlecchino,"Chevreuse, Lan Yan, Rosaria","21st January, 2025 to 11th February, 2025"
128,Dawn's Drifting Reverie,Mizuki,"Gorou, Sayu, Xiangling","12th February, 2025 to 4th March, 2025"
129,Romaritime Meluserenity,Sigewinne,"Gorou, Sayu, Xiangling","12th February, 2025 to 4th March, 2025"
130,Chanson of Many Waters,Furina,"Charlotte, Chongyun, Mika","4th March, 2025 to 25th March, 2025"
131,Tempestuous Destiny,Wriothesley,"Charlotte, Chongyun, Mika","4th March, 2025 to 25th March, 2025"

In [2]:
HSR_Banner = pd.read_csv('hsr_banner_history_eurogamer.csv')
HSR_Banner

,Banner Name,5-Star Character,4-Star Characters,Banner Dates
0,Butterfly on Swordtip,Seele,"Hook, Natasha, Pela","26th April, 2023 to 17th May, 2023"
1,Swirl of Heavenly Spear,Jing Yuan,"March 7th, Sushang, Tingyun","17th May, 2023 to 6th June, 2023"
2,Contract Zero,Silver Wolf,"Asta, Dan Heng, Serval","7th June, 2023 to 28th June, 2023"
3,Laic Pursuit,Luocha,"Pela, Qingque, Yukong","28th June, 2023 to 18th July, 2023"
4,A Lost Soul,Blade,"Arlan, Natasha, Sushang","19th July, 2023 to 9th August, 2023"
...,...,...,...,...
59,Indelible Coterie,Silver Wolf,"Hanya, Sushang, Tingyun","5th February, 2025 to 25th February, 2025"
60,Back to Fons et Origo,Tribbie,"Guinaifen, Hook, Lynx","26th February, 2025 to 19th March, 2025"
61,"Earth Hurled, Ether Curled",Yunli,"Guinaifen, Hook, Lynx","26th February, 2025 to 19th March, 2025"
62,Fiery Lionheart,Mydei,"Arlan, Natasha, Xueyi","19th March, 2025 to 8th April, 2025"
63,Bloom in Gloom,Huohuo,"Arlan, Natasha, Xueyi","19th March, 2025 to 8th April, 2025"